version: '3.8'

services:
  # PostgreSQL 服务
  postgres:
    image: postgres:15
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}              # 数据库用户名
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}      # 密码
      POSTGRES_DB: ${POSTGRES_DB}                  # 数据库名
      TZ: ${TZ}                                     # 时区设置
    ports:
      - "5432:5432"  # PostgreSQL 默认端口
    volumes:
      - ${HOME}/docker/postgresql/data:/var/lib/postgresql/data     # 数据挂载
      - ${HOME}/docker/postgresql/logs:/var/log/postgresql          # 日志挂载
      - ${HOME}/docker/postgresql/config:/etc/postgresql            # 配置文件挂载

  # n8n 服务
  n8n:
    image: n8nio/n8n:latest  # 使用官方最新版n8n镜像
    container_name: n8n      # 容器名称
    restart: always          # 总是自动重启
    depends_on:
      - postgres            # 依赖的PostgreSQL服务（确保数据库先启动）
    
    # 环境变量配置
    environment:
      # 数据库配置
      DB_TYPE: postgresdb                          # 数据库类型
      DB_POSTGRESDB_HOST: postgres                 # 数据库主机名
      DB_POSTGRESDB_PORT: 5432                    # 数据库端口
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}      # 数据库名称（从环境变量获取）
      DB_POSTGRESDB_USER: ${POSTGRES_USER}        # 数据库用户（从环境变量获取）
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD} # 数据库密码（从环境变量获取）
      
      # 本地化设置
      N8N_DEFAULT_LOCALE: ${N8N_LANG}  # 界面语言（如zh-cn）
      GENERIC_TIMEZONE: ${TZ}          # 时区设置
      TZ: ${TZ}                       # 系统时区
      
      # 基础认证配置（保护后台）
      N8N_BASIC_AUTH_ACTIVE: true                     # 启用基础认证
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}     # 管理员用户名（从环境变量获取）
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD} # 管理员密码（从环境变量获取）
      
      # 邮件服务配置（注释状态）
      # N8N_SMTP_HOST: ${N8N_SMTP_HOST}      # SMTP服务器
      # N8N_SMTP_PORT: ${N8N_SMTP_PORT}      # SMTP端口
      # N8N_SMTP_USER: ${N8N_SMTP_USER}      # SMTP用户名
      # N8N_SMTP_PASS: ${N8N_SMTP_PASS}      # SMTP密码
      # N8N_SMTP_SENDER: ${N8N_SMTP_SENDER}  # 发件人邮箱
      # N8N_SMTP_SSL: true                   # 启用SSL
      
      # Webhook穿透配置（注释状态）
      # N8N_HOST: n8n.local               # 自定义域名
      # WEBHOOK_URL: ${N8N_TUNNEL_URL}    # 穿透URL
    
    # 端口映射
    ports:
      - "5678:5678"  # 将容器内5678端口映射到宿主机
    
    # 数据卷挂载
    volumes:
      - ${HOME}/docker/n8n/data:/home/node/.n8n              # 核心数据存储
      - ${HOME}/docker/n8n/logs:/var/log/n8n                 # 日志目录
      - ${HOME}/docker/n8n/config:/home/node/n8n-config      # 配置文件目录
      - ${HOME}/docker/n8n/files:/home/node/files            # 用户上传文件存储
      - ${HOME}/docker/n8n/ui/dist:/usr/local/lib/node_modules/n8n/node_modules/n8n-editor-ui/dist  # UI自定义目录配置中文UI
